/* Progressive enhancement: the reference text and illustrations work without JavaScript. */
(()=>{'use strict';
 const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
 let group='all';const search=$('#formulaSearch');
 function filter(){const term=search.value.trim().toLowerCase();let count=0;$$('.formula-group').forEach(section=>{let visible=0;section.querySelectorAll('.formula-card').forEach(card=>{card.hidden=!((group==='all'||group===section.dataset.topic)&&card.dataset.search.includes(term));if(!card.hidden)visible++;});section.hidden=visible===0;count+=visible;});$('#formulaCount').textContent=`顯示 ${count} 張關係卡` ;$('#noFormulas').hidden=count>0;$$('[data-group]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.group===group)));}
 search.addEventListener('input',filter);$$('[data-group]').forEach(b=>b.addEventListener('click',()=>{group=b.dataset.group;filter();}));$('#clearFilters').addEventListener('click',()=>{group='all';search.value='';filter();});$('#printFormulas').addEventListener('click',()=>window.print());
 function revealHash(){let id;try{id=decodeURIComponent(location.hash.slice(1));}catch{return;}const target=document.getElementById(id);if(target?.closest('.formula-group')){group='all';search.value='';filter();target.scrollIntoView();}}
 window.addEventListener('hashchange',revealHash);revealHash();
 const models=window.FormulaModels,kind=$('#calculatorKind'),fields=$('#calculatorFields'),result=$('#calculationResult');
 for(const [id,m] of Object.entries(models.definitions)){const option=document.createElement('option');option.value=id;option.textContent=m.title;kind.append(option);}
 function renderFields(){fields.replaceChildren();const m=models.definitions[kind.value];m.fields.forEach(([id,title,value])=>{const label=document.createElement('label'),input=document.createElement('input');label.textContent=title;input.id='calc-'+id;input.type='number';input.step='any';input.inputMode='decimal';input.value=value;input.required=true;input.setAttribute('aria-describedby','calculatorCondition');label.append(input);fields.append(label);});$('#calculatorCondition').textContent=m.condition;result.classList.remove('error');result.textContent='輸入完成後，按「計算並看步驟」。';}
 kind.addEventListener('change',renderFields);fields.addEventListener('input',()=>{result.classList.remove('error');result.textContent='數值已變更，請重新計算。';});renderFields();
 $('#formulaCalculator').noValidate=true;$('#formulaCalculator').addEventListener('submit',event=>{event.preventDefault();try{const answer=models.calculate(kind.value,[...fields.querySelectorAll('input')].map(i=>i.value));result.textContent=answer.text;result.classList.remove('error');}catch(error){result.textContent=error.message;result.classList.add('error');}});
 const answers=new Map();
 function renderQuiz(){answers.clear();$('#conceptQuestions').replaceChildren();models.quiz.forEach((q,i)=>{const article=document.createElement('article');article.className='quiz-item';const fieldset=document.createElement('fieldset'),legend=document.createElement('legend'),options=document.createElement('div'),feedback=document.createElement('p');legend.textContent=`${i+1}. ${q.q}`;options.className='quiz-options';feedback.className='quiz-feedback';feedback.setAttribute('role','status');q.options.forEach((label,j)=>{const button=document.createElement('button');button.type='button';button.textContent=label;button.setAttribute('aria-pressed','false');button.addEventListener('click',()=>{if(answers.has(i))return;answers.set(i,j);options.querySelectorAll('button').forEach((b,k)=>{b.disabled=true;b.setAttribute('aria-pressed',String(k===j));});const correct=j===q.answer;feedback.textContent=(correct?'答對了。':'再釐清一次：正確是「'+q.options[q.answer]+'」。')+q.why;feedback.className='quiz-feedback '+(correct?'correct':'incorrect');$('#conceptScore').textContent=`已完成 ${answers.size}／6 題，答對 ${[...answers].filter(([n,a])=>models.quiz[n].answer===a).length} 題。`;});options.append(button);});fieldset.append(legend,options);article.append(fieldset,feedback);$('#conceptQuestions').append(article);});$('#conceptScore').textContent='尚未作答';}
 $('#resetConcepts').addEventListener('click',renderQuiz);renderQuiz();
})();
