/* Pure teaching models shared by the browser and verification script. */
(function(root){
  const range=(key,label,min,max,value,step=1,unit='')=>({key,label,min,max,value,step,unit});
  const select=(key,label,options,value)=>({key,label,options,value});
  const rounded=(n,d=2)=>Number(n.toFixed(d));
  const series=(count,step,fn)=>Array.from({length:count},(_,i)=>({x:i*step,y:rounded(fn(i*step),3)}));
  const elements=['','氫 H','氦 He','鋰 Li','鈹 Be','硼 B','碳 C','氮 N','氧 O','氟 F','氖 Ne','鈉 Na','鎂 Mg','鋁 Al','矽 Si','磷 P','硫 S','氯 Cl','氬 Ar'];
  const models={
    atom:{title:'原子組裝台',question:'先猜猜：只改變中子數，元素名稱會改變嗎？',note:'粒子圓點只表示數量；不是原子的真實比例或電子軌道。',controls:[range('p','質子數',1,18,6),range('n','中子數',0,22,6),range('e','電子數',0,20,6)],
      calculate(v){const charge=v.p-v.e;return {value:elements[v.p],detail:`質量數 ${v.p+v.n}；電荷數 ${charge>0?'+':''}${charge}。${charge===0?'這是中性原子。':charge>0?'電子比質子少，是陽離子。':'電子比質子多，是陰離子。'}同一元素由質子數決定；只改中子數會成為同位素。`,bars:[['質子',v.p],['中子',v.n],['電子',v.e]],unit:'個',scene:'atom',particles:v};}},
    reaction:{title:'化學式配平工作台',question:'改動係數，讓反應前後每一種原子的數量都相同。',note:'以水的生成為模型；只調整式子前的係數，不改化學式右下角數字。請勿自行混合或點燃氣體。',controls:[range('h','H₂ 的係數',1,6,1),range('o','O₂ 的係數',1,6,1),range('w','H₂O 的係數',1,6,1)],
      calculate(v){const balanced=v.h*2===v.w*2&&v.o*2===v.w;return {value:balanced?'原子數已平衡':'還未平衡',detail:`${v.h} H₂ ＋ ${v.o} O₂ → ${v.w} H₂O。氫：左 ${2*v.h}、右 ${2*v.w}；氧：左 ${2*v.o}、右 ${v.w}。${balanced?'最簡整數係數為 2：1：2。':'觀察哪一種原子還不相等，再調整。'}`,bars:[['左側氫',2*v.h],['右側氫',2*v.w],['左側氧',2*v.o],['右側氧',v.w]],unit:'個原子'};}},
    redox:{title:'誰能取走氧？',question:'比較金屬活動性，預測加熱後氧會留在哪一種金屬上。',note:'此處用鋅＞鐵＞銅的氧化傾向作簡化判斷；實際反應還受溫度、接觸與反應條件限制。',controls:[select('metal','加入的金屬',[['Zn','鋅'],['Fe','鐵'],['Cu','銅']],'Zn'),select('oxide','氧化物中的金屬',[['Zn','氧化鋅'],['Fe','氧化鐵'],['Cu','氧化銅']],'Cu')],
      calculate(v){const rank={Zn:3,Fe:2,Cu:1},name={Zn:'鋅',Fe:'鐵',Cu:'銅'},yes=rank[v.metal]>rank[v.oxide];return {value:yes?'較活潑金屬可奪氧':'不預期發生奪氧',detail:yes?`${name[v.metal]}比${name[v.oxide]}活潑，在適當加熱條件下可取得氧而被氧化；原氧化物失去氧而被還原。`:`${name[v.metal]}未比${name[v.oxide]}活潑，依此模型不能把氧從該氧化物取走。`,bars:[['鋅',3],['鐵',2],['銅',1]],unit:'活動性順序示意（非測量值）',scene:'transfer',transfer:yes};}},
    acid:{title:'酸鹼中和滴定台',question:'固定兩種溶液的濃度，改變體積，預測最後呈酸性、鹼性或中性。',note:'25°C；兩液皆為 0.10 mol/L 的強酸鹽酸與強鹼氫氧化鈉，假設體積可相加。數值供觀察；不需背熟對數計算。',controls:[range('acid','鹽酸體積',10,100,40,10,'mL'),range('base','氫氧化鈉體積',10,100,40,10,'mL')],
      calculate(v){const excess=.1*(v.acid-v.base),c=Math.abs(excess)/(v.acid+v.base),ph=excess===0?7:excess>0?-Math.log10(c):14+Math.log10(c);return {value:`pH 約 ${rounded(ph)}`,detail:`原有 H⁺ ${rounded(v.acid*.1)} mmol、OH⁻ ${rounded(v.base*.1)} mmol，1：1 中和。${excess===0?'恰好中和，溶液含水及氯化鈉。':`剩餘 ${excess>0?'H⁺':'OH⁻'} ${rounded(Math.abs(excess))} mmol，呈${excess>0?'酸':'鹼'}性。`}`,bars:[['原有 H⁺',v.acid*.1],['原有 OH⁻',v.base*.1],['剩餘 H⁺',Math.max(0,excess)],['剩餘 OH⁻',Math.max(0,-excess)]],unit:'mmol',scene:'ph',ph};}},
    rate:{title:'氣體生成速率實驗',question:'同樣的反應物總量，改變速率，最後生成的氣體總量會不同嗎？',note:'教學模型：反應進度＝100×(1−e⁻ᵏᵗ)。只呈現「快慢不同、終點相同」，數值不是實測或通用化學定律。',controls:[select('factor','反應條件',[[1,'基準'],[2,'顆粒較細（模型速率 ×2）'],[3,'加入適當催化劑（模型速率 ×3）']],1),range('time','觀察時間',0,120,30,5,'s')],
      calculate(v){const f=t=>100*(1-Math.exp(-.04*v.factor*t));return {value:`完成 ${rounded(f(v.time),1)}%`,detail:'曲線越陡代表該時刻反應越快。加速不代表產物無限增加；三種條件都接近同樣的 100% 終點。催化劑也不改變平衡常數。',line:series(25,5,f),marker:{x:v.time,y:f(v.time)},xLabel:'時間（s）',yLabel:'反應進度（%）'};}},
    organic:{title:'碳鏈與完全燃燒',question:'每增加一個碳，開鏈飽和烴需要多幾個氫？完全燃燒後碳去哪裡？',note:'只適用開鏈飽和烴，不包含環狀或不飽和烴。這是分子及係數示意，非實際燃燒操作。',controls:[range('carbon','每個分子的碳原子數',1,6,2)],
      calculate(v){const n=v.carbon;return {value:`C${n===1?'':n}H${2*n+2}`,detail:`開鏈飽和烴的氫數＝2n＋2。完全燃燒：2 C${n===1?'':n}H${2*n+2} ＋ ${3*n+1} O₂ → ${2*n} CO₂ ＋ ${2*n+2} H₂O。碳原子數並未消失。`,bars:[['分子中的 C',n],['分子中的 H',2*n+2]],unit:'個原子',scene:'chain',carbon:n};}},
    pressure:{title:'液體壓力與浮力槽',question:'物體完全浸沒後，放得更深，浮力一定更大嗎？',note:'g＝10 N/kg；均勻、近似不可壓縮的液體。壓力是液體造成的表壓，不含大氣壓；物體完全浸沒。',controls:[range('depth','深度',0,5,2,.5,'m'),range('density','液體密度',800,1200,1000,100,'kg/m³'),range('volume','排開液體體積',100,500,200,50,'cm³')],
      calculate(v){const p=v.density*10*v.depth,b=v.density*10*v.volume/1e6;return {value:`液體壓力 ${p} Pa`,detail:`p＝ρgh＝${v.density}×10×${v.depth}＝${p} Pa；浮力＝ρgV＝${rounded(b)} N。完全浸沒後，若液體密度與排水體積不變，改變深度不改變浮力。`,line:series(11,.5,d=>v.density*10*d),marker:{x:v.depth,y:p},xLabel:'深度（m）',yLabel:'液體壓力（Pa）',scene:'water',depth:v.depth};}},
    motion:{title:'速度—時間圖實驗',question:'斜率和圖下的有向面積，各自代表什麼？',note:'沿一直線作等加速度運動；向右為正，初始位置 x＝0。面積可為負，代表向負方向的位移。',controls:[range('speed','初速度',0,12,4,1,'m/s'),range('accel','加速度',-2,2,1,.5,'m/s²'),range('time','運動時間',0,10,4,1,'s')],
      calculate(v){const end=v.speed+v.accel*v.time,x=v.speed*v.time+.5*v.accel*v.time*v.time;return {value:`末速度 ${rounded(end)} m/s`,detail:`位移＝初速度×時間＋½×加速度×時間²＝${rounded(x)} m。速度圖斜率＝${v.accel} m/s²。${end<0?'末速度為負，物體此刻向左；路程不能直接用有向面積代替。':'注意速率是速度的大小，不帶方向。'}`,line:series(11,1,t=>v.speed+v.accel*t),marker:{x:v.time,y:end},xLabel:'時間（s）',yLabel:'速度（m/s）'};}},
    newton:{title:'推車受力實驗',question:'相同推力，增加質量會讓加速度如何改變？',note:'水平運動；右為正。滑動摩擦力假設固定向左且不超過推力。本模型討論向右滑動時，不用來推斷靜摩擦。',controls:[range('force','向右推力',10,50,20,5,'N'),range('friction','向左滑動摩擦力',0,10,5,1,'N'),range('mass','車與載物總質量',1,10,5,1,'kg')],
      calculate(v){const net=v.force-v.friction,a=net/v.mass;return {value:`加速度 ${rounded(a)} m/s²`,detail:`合力＝${v.force}−${v.friction}＝${net} N；a＝F合/m＝${net}/${v.mass}。合力為零代表速度不變，不一定靜止。`,bars:[['右向推力',v.force],['左向摩擦力',v.friction],['右向合力',net]],unit:'N',scene:'force',force:v.force,friction:v.friction};}},
    energy:{title:'斜坡上的能量帳本',question:'高度下降時，重力位能去哪裡？加入摩擦後總能量還守恆嗎？',note:'g＝10 N/kg，從 10 m 高處由靜止釋放；損耗比例是已失去重力位能中轉為內能的比例。',controls:[range('height','目前高度',0,10,6,1,'m'),range('mass','物體質量',1,5,2,1,'kg'),range('loss','轉為內能的比例',0,60,0,10,'%')],
      calculate(v){const initial=v.mass*100,pe=v.mass*10*v.height,thermal=(initial-pe)*v.loss/100,ke=initial-pe-thermal;return {value:`速率 ${rounded(Math.sqrt(2*ke/v.mass))} m/s`,detail:`起初 ${initial} J＝重力位能 ${pe} J＋動能 ${rounded(ke)} J＋轉出的內能 ${rounded(thermal)} J。有摩擦時力學能可能減少，但把內能也算入後總能量不變。`,bars:[['重力位能',pe],['動能',ke],['內能',thermal]],unit:'J',scene:'ramp',height:v.height};}},
    circuit:{title:'串並聯電路工作台',question:'相同電源下，把兩個電阻由串聯改為並聯，總電流如何變化？',note:'理想電源、導線電阻忽略；電阻維持定值。圖中數值為直流穩態，請勿使用家用插座實作。',controls:[select('mode','連接方式',[['series','串聯'],['parallel','並聯']],'series'),range('voltage','電源電壓',1,12,6,1,'V'),range('r1','電阻 R₁',1,12,3,1,'Ω'),range('r2','電阻 R₂',1,12,6,1,'Ω')],
      calculate(v){const r=v.mode==='series'?v.r1+v.r2:v.r1*v.r2/(v.r1+v.r2),i=v.voltage/r,i1=v.mode==='series'?i:v.voltage/v.r1,i2=v.mode==='series'?i:v.voltage/v.r2;return {value:`總電流 ${rounded(i)} A`,detail:`等效電阻 ${rounded(r)} Ω。${v.mode==='series'?'串聯各處電流相同，電壓依電阻分配。':'並聯兩支路電壓相同，總電流為各支路電流之和。'}`,bars:[['總電流',i],['R₁ 電流',i1],['R₂ 電流',i2]],unit:'A',scene:'circuit',parallel:v.mode==='parallel'};}},
    power:{title:'用電量與電費估算',question:'電器功率減半、使用時間加倍，用電量會改變嗎？',note:'以標示功率持續運作，忽略啟停；單價由你設定，只是算例，不是台電即時費率。電流以純電阻、110 V 估算。',controls:[range('watts','電器功率',100,1500,800,100,'W'),range('hours','每日使用時間',1,12,3,1,'h'),range('days','使用天數',1,30,10,1,'天'),range('price','假設每度單價',1,8,3,1,'元/kWh')],
      calculate(v){const e=v.watts/1000*v.hours*v.days;return {value:`用電 ${rounded(e)} 度`,detail:`電能＝${v.watts/1000} kW×${v.hours} h/天×${v.days} 天＝${rounded(e)} kWh；假設電費 ${rounded(e*v.price)} 元。運作電流約 ${rounded(v.watts/110)} A；多台同時使用時要加總電流。`,line:series(v.days+1,1,d=>v.watts/1000*v.hours*d),xLabel:'天數',yLabel:'累積用電（kWh）'};}},
    water:{title:'集水區降雨分配',question:'降雨相同，鋪面增加使入滲減少時，地表逕流可能怎麼變？',note:'單次降雨的簡化水量帳本，忽略蒸發與暫存；土壤、坡度、前期含水量也會影響實際入滲。',controls:[range('rain','降雨量',10,100,60,10,'mm'),range('area','集水區面積',1,10,2,1,'km²'),range('infiltration','入滲比例',10,90,60,10,'%')],
      calculate(v){const total=v.rain*v.area*1000,soil=total*v.infiltration/100;return {value:`地表逕流 ${Math.round(total-soil).toLocaleString()} m³`,detail:`1 mm 降雨落在 1 km² 上＝1000 m³。總降水量 ${total.toLocaleString()} m³＝入滲 ${Math.round(soil).toLocaleString()}＋逕流 ${Math.round(total-soil).toLocaleString()}。此模型不表示所有入滲水都立即成為地下水。`,bars:[['降水',total],['入滲',soil],['逕流',total-soil]],unit:'m³',scene:'cycle'};}},
    seismic:{title:'P、S 波到站計時',question:'P 波先到、S 波後到；兩者時間差越大，測站離震源越近還是越遠？',note:'均勻介質直線傳播模型：P 波 6 km/s、S 波 3.5 km/s。算出的是震源距，不等於所有情況下的震央距。',controls:[range('distance','震源到測站距離',30,600,210,30,'km')],
      calculate(v){const p=v.distance/6,s=v.distance/3.5;return {value:`S−P 時差 ${rounded(s-p)} s`,detail:`P 波到時 ${rounded(p)} s，S 波到時 ${rounded(s)} s。單一測站只能限制距離，不能單獨決定方向；多個測站資料才能協助定位。`,bars:[['P 波到時',p],['S 波到時',s],['S−P 差',s-p]],unit:'s',scene:'waves',distance:v.distance};}},
    moon:{title:'月相觀察台',question:'月球始終約一半被太陽照亮，為什麼地球上看到的亮面比例會變？',note:'由地球北極上方看，太陽在右；忽略軌道傾角只畫幾何關係。實際月球軌道有傾角，所以不會每月都有日月食。',controls:[range('phase','月相位置',0,7,2,1,'／8 圈')],
      calculate(v){const names=['朔／新月','眉月','上弦月','盈凸月','望／滿月','虧凸月','下弦月','殘月'],angle=v.phase*Math.PI/4,lit=(1-Math.cos(angle))/2;return {value:names[v.phase],detail:`月齡約 ${rounded(v.phase*29.53/8,1)} 天；從地球看到的月面約 ${rounded(lit*100)}% 明亮。月相来自日、地、月相對位置，不是地球影子遮住月亮。`,bars:[['可見亮面',lit*100],['可見暗面',100-lit*100]],unit:'%',scene:'moon',angle,lit};}},
    magnet:{title:'電磁感應探究台',question:'磁鐵停在導線圈旁就會持續發電嗎？試試改變相對運動。',note:'理想相對比較，刻度為任意單位，不是實際電壓。假定磁通量變化率與設定速率成正比；速度 0 時沒有感應電動勢。',controls:[range('turns','線圈匝數',20,100,40,20,'匝'),range('speed','相對移動速率',0,4,1,1,'相對單位'),select('direction','移動方向',[[1,'接近'],[-1,'遠離']],1),select('pole','面向線圈的磁極',[[1,'N 極'],[-1,'S 極']],1)],
      calculate(v){const emf=v.turns/20*v.speed*v.direction*v.pole;return {value:emf===0?'沒有感應電動勢':`表頭讀數 ${emf>0?'+':''}${emf}`,detail:'本模型把 N 極接近定為正。移動方向反轉或磁極互換，感應方向反轉；兩者同時改變則方向不變。匝數、磁通量變化速率較大，感應電動勢較大。閉合迴路才有持續的感應電流。',bars:[['感應表頭',emf]],unit:'任意單位',scene:'magnet',emf};}},
    weather:{title:'降溫、露點與相對溼度',question:'水氣含量相同，空氣降溫時相對溼度會上升還是下降？',note:'簡化表格模型，假設每立方公尺氣塊體積固定。飽和水氣量取近似值；達飽和後多出的水氣凝結。',controls:[select('temperature','氣溫',[[10,'10°C'],[15,'15°C'],[20,'20°C'],[25,'25°C'],[30,'30°C']],25),range('vapor','起初每 m³ 水氣質量',2,20,10,1,'g/m³')],
      calculate(v){const cap={10:9.4,15:12.8,20:17.3,25:23,30:30.4}[v.temperature],remain=Math.min(v.vapor,cap),rh=remain/cap*100;return {value:`相對溼度約 ${rounded(rh,1)}%`,detail:`此溫度的飽和水氣量約 ${cap} g/m³。${v.vapor>cap?`約 ${rounded(v.vapor-cap)} g/m³ 水氣凝結。`:'尚未超過飽和水氣量。'}相對溼度 100% 表示達飽和，不代表空氣全部是水氣。`,bars:[['原有水氣',v.vapor],['飽和水氣量',cap],['凝結量',Math.max(0,v.vapor-cap)]],unit:'g/m³',scene:'cloud',rh};}},
    climate:{title:'能源選擇與排放帳本',question:'同樣提供電力，節約用電與提高低排放電源比例，各能減少多少排放？',note:'教學假設：高排放電源 0.8 kg CO₂e/kWh、低排放電源 0.05 kg CO₂e/kWh，包含簡化生命週期概念；不是臺灣即時電力排放係數。',controls:[range('demand','原本用電量',100,1000,500,100,'kWh'),range('saving','節電比例',0,50,20,10,'%'),range('low','低排放電源比例',0,100,40,10,'%')],
      calculate(v){const used=v.demand*(1-v.saving/100),factor=.8*(1-v.low/100)+.05*v.low/100,emissions=used*factor;return {value:`估計排放 ${rounded(emissions)} kg CO₂e`,detail:`實際用電 ${used} kWh，平均排放係數 ${rounded(factor,3)} kg CO₂e/kWh。與原先全部使用高排放電源的 ${v.demand*.8} kg 相比，減少 ${rounded(v.demand*.8-emissions)} kg。低排放不是零環境成本，仍要評估土地、材料與生態。`,bars:[['原本排放',v.demand*.8],['改善後排放',emissions]],unit:'kg CO₂e',scene:'earth'};}}
  };
  root.ScienceModels=models;
  if(typeof module!=='undefined')module.exports=models;
})(typeof globalThis!=='undefined'?globalThis:this);
